include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # بنیادی rules
    - avoid_print
    - prefer_single_quotes
    - unnecessary_new
    
    # اضافی مفید rules
    - always_use_package_imports
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    
  errors:
    # مخصوص غلطیوں کے لیے درجہ بندی
    missing_required_param: error
    # ❌ 'invalid_required_param' کو ہٹا دیں یا درست کریں
    
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
