me: aladdin_app
description: A demo Flutter app to showcase Aladdin
publish_to: 'none' # چونکہ یہ صرف GitHub پر ہے، pub.dev پر publish نہیں ہوگا

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Default Flutter icon package
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


