import 'dart:convert';
import 'package:http/http.dart' as http;

class GeminiService {
  // ✅ یہ API key آپ Google AI Studio سے مفت لے سکتے ہیں
  static const String apiKey = 'AIzaSyAAAAAAAAAAAAAAAAAAAAAAAAAAA'; // اپنی key ڈالیں
  static const String apiUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent';
  
  static Future<String> generateFlutterCode(String userPrompt) async {
    try {
      // ✅ Intelligent prompt بنائیں
      String smartPrompt = """
You are a Flutter expert. Create complete, runnable Flutter code for: $userPrompt

Requirements:
- Use Material Design
- Make it responsive
- Add proper imports
- Return only Dart code without explanations
- The code should compile successfully

Return the code in a single code block.
""";

      final response = await http.post(
        Uri.parse('$apiUrl?key=$apiKey'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          "contents": [
            {
              "parts": [
                {"text": smartPrompt}
              ]
            }
          ],
          "generationConfig": {
            "temperature": 0.7,
            "topK": 40,
            "topP": 0.95,
            "maxOutputTokens": 2048,
          }
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final generatedText = data['candidates'][0]['content']['parts'][0]['text'];
        
        // ✅ صرف کوڈ نکالیں (explanations ہٹائیں)
        return _extractCode(generatedText);
      } else {
        throw Exception('Gemini API error: ${response.statusCode} - ${response.body}');
      }
    } catch (e) {
      // ✅ Fallback response
      return _getFallbackCode(userPrompt);
    }
  }

  // ✅ AI response سے صرف کوڈ نکالیں
  static String _extractCode(String generatedText) {
    if (generatedText.contains('```dart')) {
      return generatedText.split('```dart')[1].split('```')[0].trim();
    } else if (generatedText.contains('```')) {
      return generatedText.split('```')[1].split('```')[0].trim();
    } else {
      return generatedText.trim();
    }
  }

  // ✅ Fallback code اگر API کام نہ کرے
  static String _getFallbackCode(String prompt) {
    return """
// 🌟 Flutter Code Generated by AI
// For: $prompt

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AI Generated App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Your AI App'),
        backgroundColor: Colors.deepPurple,
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.auto_awesome, size: 50, color: Colors.deepPurple),
            SizedBox(height: 20),
            Text(
              'AI App Factory',
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 10),
            Text(
              'App for: $prompt',
              style: TextStyle(fontSize: 16),
              textAlign: TextAlign.center,
            ),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: () {},
              child: Text('Get Started'),
            ),
          ],
        ),
      ),
    );
  }
}
""";
  }
}
