import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

class GitHubService {
  static const String _tokenKey = 'github_token';
  
  Future<String?> getSavedToken() async { // ✅ method شامل کریں
    try {
      final prefs = await SharedPreferences.getInstance();
      return prefs.getString(_tokenKey);
    } catch (e) {
      return null;
    }
  }

  Future<void> saveToken(String token) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_tokenKey, token.trim());
    } catch (e) {
      throw Exception('Token save failed: $e');
    }
  }

  // GitHub پر repository بنانا
  Future<String> createRepository(String repoName, String code) async {
  final token = await getSavedToken();
  if (token == null || token.isEmpty) {
    return '⚠️ اپنا کنکشن جوڑیں — GitHub ٹوکن سیٹ نہیں ہے۔';
  }

  try {
    final response = await http.post(
      Uri.parse('https://api.github.com/user/repos'),
      headers: {
        'Authorization': 'token $token',
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: jsonEncode({
        'name': repoName.replaceAll(' ', '_'),
        'description': 'Auto-generated by Aladdin AI App Factory',
        'private': false,
        'auto_init': false,
      }),
    );

    if (response.statusCode == 201) {
      final repoData = jsonDecode(response.body);
      return '✅ ریپوزٹری بن گئی: ${repoData['html_url']}';
    } else if (response.statusCode == 401) {
      return '❌ GitHub ٹوکن غلط ہے۔ براہ کرم نیا ٹوکن درج کریں۔';
    } else {
      return '⚠️ GitHub Error: ${response.statusCode}';
    }
  } catch (e) {
    return '⚠️ کنکشن ناکام — براہ کرم اپنا انٹرنیٹ چیک کریں۔';
  }
}

