import 'dart:io';

class LocalAPKBuilder {
  static Future<File> buildAPK(String projectName, String flutterCode) async {
    try {
      print("=== APK BUILD STARTED ===");
      
      // 1. Temporary folder بنائیں
      final tempDir = Directory('/storage/emulated/0/AppFactory/$projectName');
      if (await tempDir.exists()) {
        await tempDir.delete(recursive: true);
      }
      await tempDir.create(recursive: true);
      
      print("Temporary directory created: ${tempDir.path}");

      // 2. lib فولڈر بنائیں
      final libDir = Directory('${tempDir.path}/lib');
      await libDir.create(recursive: true);

      // 3. main.dart فائل میں کوڈ لکھیں
      final mainFile = File('${libDir.path}/main.dart');
      await mainFile.writeAsString(flutterCode);
      print("main.dart file written");

      // 4. pubspec.yaml بنائیں
      final pubspecFile = File('${tempDir.path}/pubspec.yaml');
      await pubspecFile.writeAsString('''
name: $projectName
description: Generated by Aladdin App Factory
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
''');
      print("pubspec.yaml file written");

      // 5. Flutter build process
      print("Starting Flutter build...");
      
      // پہلے flutter create (اگر ضرورت ہو)
      final createResult = await Process.run('flutter', ['create', '.'], 
          workingDirectory: tempDir.path);
      
      if (createResult.exitCode != 0) {
        print("Flutter create failed: ${createResult.stderr}");
      }

      // پھر APK build
      final buildResult = await Process.run('flutter', 
          ['build', 'apk', '--release'], 
          workingDirectory: tempDir.path);

      if (buildResult.exitCode == 0) {
        final apkFile = File('${tempDir.path}/build/app/outputs/flutter-apk/app-release.apk');
        if (await apkFile.exists()) {
          print("=== APK BUILD SUCCESSFUL ===");
          print("APK Location: ${apkFile.path}");
          return apkFile;
        } else {
          throw Exception('APK file not found at expected location');
        }
      } else {
        throw Exception('Build failed: ${buildResult.stderr}');
      }
    } catch (e) {
      print("=== APK BUILD FAILED ===");
      print("Error: $e");
      throw Exception('APK build error: $e');
    }
  }

  // APK file کو کسی accessible location پر copy کرنے کے لیے
  static Future<File> copyToDownloads(File apkFile, String projectName) async {
    try {
      final downloadsDir = Directory('/storage/emulated/0/Download/AppFactory');
      await downloadsDir.create(recursive: true);
      
      final newFile = File('${downloadsDir.path}/$projectName.apk');
      await apkFile.copy(newFile.path);
      
      print("APK copied to: ${newFile.path}");
      return newFile;
    } catch (e) {
      throw Exception('Copy failed: $e');
    }
  }
}
