import 'dart:io';

class TermuxService {
  static Future<String> buildAPK(String projectName, String flutterCode) async {
    try {
      // ✅ Download/aladdin_projects میں project بنائیں
      final downloadDir = Directory('/storage/emulated/0/Download/aladdin_projects');
      if (!await downloadDir.exists()) {
        await downloadDir.create(recursive: true);
      }
      
      final projectDir = Directory('${downloadDir.path}/$projectName');
      if (await projectDir.exists()) {
        await projectDir.delete(recursive: true);
      }
      await projectDir.create(recursive: true);
      
      // lib ڈائریکٹری
      final libDir = Directory('${projectDir.path}/lib');
      await libDir.create(recursive: true);
      
      // main.dart فائل
      final mainFile = File('${libDir.path}/main.dart');
      await mainFile.writeAsString(flutterCode);
      
      // pubspec.yaml
      final pubspecFile = File('${projectDir.path}/pubspec.yaml');
      await pubspecFile.writeAsString('''
name: $projectName
description: Generated by Aladdin App Factory
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
''');

      // ✅ اب Termux کو command push کریں
      final bridgeDir = Directory('/storage/emulated/0/Download/Aladdin');
      if (!await bridgeDir.exists()) {
        await bridgeDir.create(recursive: true);
      }

      final cmdFile = File('${bridgeDir.path}/cmd.txt');
      await cmdFile.writeAsString('''
cd ~/storage/downloads/aladdin_projects/$projectName &&
flutter build apk --release --no-tree-shake-icons
''');

      return "✅ Project ready & build command sent to Termux!";

    } catch (e) {
      return "❌ Error: $e";
    }
  }
}

