import 'dart:io';

class TermuxService {
  static Future<String> buildAPK(String projectName, String flutterCode) async {
    try {
      print("🚀 Starting APK build process...");
      
      // 1. Temporary directory بنائیں
      final tempDir = Directory('/data/data/com.termux/files/home/projects/$projectName');
      if (await tempDir.exists()) {
        await tempDir.delete(recursive: true);
      }
      await tempDir.create(recursive: true);
      
      // 2. Flutter code فائل میں لکھیں
      final mainFile = File('${tempDir.path}/lib/main.dart');
      await mainFile.create(recursive: true);
      await mainFile.writeAsString(flutterCode);
      
      // 3. pubspec.yaml بنائیں
      final pubspecFile = File('${tempDir.path}/pubspec.yaml');
      await pubspecFile.writeAsString('''
name: $projectName
description: Generated by Aladdin App Factory
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
''');

      // 4. Termux میں Flutter build command بھیجیں
      final result = await Process.run('sh', [
        '-c',
        '''
        cd ${tempDir.path} &&
        flutter clean &&
        flutter pub get &&
        flutter build apk --release
        '''
      ]);

      if (result.exitCode == 0) {
        final apkFile = File('${tempDir.path}/build/app/outputs/flutter-apk/app-release.apk');
        if (await apkFile.exists()) {
          return "✅ APK built successfully!\n📍 Location: ${apkFile.path}";
        } else {
          return "❌ APK file not found";
        }
      } else {
        return "❌ Build failed: ${result.stderr}";
      }
    } catch (e) {
      return "❌ APK build error: $e";
    }
  }
}
