import 'dart:io';

class TermuxService {
  static Future<String> buildAPK(String projectName, String flutterCode) async {
    try {
      print("🚀 APK بنانے کا پروسیس شروع...");

      // ✅ پہلے Download folder میں ڈائریکٹری بنائیں
      final downloadDir = Directory('/storage/emulated/0/Download/aladdin_projects');
      if (!await downloadDir.exists()) {
        await downloadDir.create(recursive: true);
      }

      final projectDir = Directory('${downloadDir.path}/$projectName');
      if (await projectDir.exists()) {
        await projectDir.delete(recursive: true);
      }
      await projectDir.create(recursive: true);

      // ✅ lib ڈائریکٹری بنائیں
      final libDir = Directory('${projectDir.path}/lib');
      await libDir.create(recursive: true);

      // ✅ main.dart فائل بنائیں
      final mainFile = File('${libDir.path}/main.dart');
      await mainFile.writeAsString(flutterCode);

      // ✅ pubspec.yaml بنائیں
      final pubspecFile = File('${projectDir.path}/pubspec.yaml');
      await pubspecFile.writeAsString('''
name: $projectName
description: Generated by Aladdin App Factory
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
''');

      // ✅ Termux میں دستی ہدایات واپس کریں
      return """
✅ **Flutter پروجیکٹ تیار ہو گیا!**

📁 **پروجیکٹ لوکیشن:**
/storage/emulated/0/Download/aladdin_projects/$projectName

📱 **APK بنانے کے لیے Termux میں یہ commands چلائیں:**

```bash
cd /storage/emulated/0/Download/aladdin_projects/$projectName
flutter clean
flutter pub get
flutter build apk --release --no-tree-shake-icons
